### PR TITLE
Include G6 license

### PR DESCRIPTION
**Pull request by disrupted**
Since we're using custom node types for the graph, we have part of the G6 source code in this repo. So let's include their license file as well.

### CODE REVIEW

**Comment by philipp94831** [comment]
What part of the code are you referring to?

**Comment by disrupted** [comment]
> What part of the code are you referring to?

Specifically [`MetricCustomNode`](https://github.com/bakdata/streams-explorer/blob/main/frontend/src/components/MetricCustomNode.tsx) and [`DashedEdge`](https://github.com/bakdata/streams-explorer/blob/main/frontend/src/components/DashedEdge.tsx)

**Comment by philipp94831** [comment]
> > What part of the code are you referring to?
> 
> Specifically [`MetricCustomNode`](https://github.com/bakdata/streams-explorer/blob/main/frontend/src/components/MetricCustomNode.tsx) and [`DashedEdge`](https://github.com/bakdata/streams-explorer/blob/main/frontend/src/components/DashedEdge.tsx)

Ok, there was not way to avoid copying that?

**Comment by disrupted** [comment]
> Ok, there was not way to avoid copying that?

I think that's the recommended way.

**Review by philipp94831 — APPROVED** [review]

**Pull request merged**
